import './style.css';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { SSAOPass } from 'three/examples/jsm/postprocessing/SSAOPass.js';
import { OutputPass } from 'three/examples/jsm/postprocessing/OutputPass.js';
import { PLAN,ROOMS,roomAt,roomById } from './plan.js';
import { validatePlan } from './navigation.js';
import { buildScene } from './scene.js';
import { WalkControls } from './controls.js';
import { createMinimap } from './minimap.js';

const $=id=>document.getElementById(id),canvas=$('scene'),viewport=$('viewport');
const descriptions={hall:'Свободный вход и компактная банкетка справа от двери.',living:'Глубокий navy-вельвет, мягкий округлый силуэт и тёплые охристые акценты. Рядом — лежанка таксы.',child:'Кровать, рабочий стол с правильно развёрнутым креслом и кошачий комплекс.',master:'Мягкое изголовье, льняной текстиль и отдельная гардеробная.',office:'Кресло у компьютера развёрнуто к столу, лаунж — к растению. Глухая стена и непрозрачная дверь.',wardrobe2:'Открытые секции, рейлы для одежды и полки в спальне.',wardrobe1:'Верхняя одежда, обувь и повседневные вещи у входа.',wc:'Машина открывается к входу; кошачий лоток стоит в дальнем углу у стены.',bath:'Ванна с внутренней чашей, подвесная тумба и светлые минеральные поверхности.'};
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xeeeae2);
const camera=new THREE.PerspectiveCamera(38,1,.08,65);camera.position.set(12,15,17);
const apartment=buildScene(scene,renderer);
const orbit=new OrbitControls(camera,canvas);orbit.target.set(5.3,0,3.6);orbit.enableDamping=true;orbit.dampingFactor=.09;orbit.minDistance=3.8;orbit.maxDistance=60;orbit.maxPolarAngle=1.35;orbit.zoomToCursor=true;orbit.update();
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,1,1,12);ao.kernelRadius=.28;ao.minDistance=.001;ao.maxDistance=.065;composer.addPass(ao);composer.addPass(new OutputPass());
let mode='plan',activeRoom=null,evening=false,palette='warm',tween=null,fps=0,frameCount=0,sampleTime=performance.now(),pixelRatio=1,frameTime=0;
const minimap=createMinimap($('minimap'),{onRoom:focusRoom});
const walk=new WalkControls(camera,canvas,{onLock:locked=>{$('walkPrompt').hidden=locked||mode!=='walk';},onChange:(p,yaw)=>{minimap.update(p.x,p.z,yaw);const r=roomAt(p.x,p.z);if(r&&r.id!==activeRoom)setActive(r.id);}});
function setActive(id){activeRoom=id;const r=roomById(id);$('roomTitle').textContent=r?r.name:'Вся квартира';$('roomKicker').textContent=r?`${r.area} / ${r.index}`:'Общий вид';$('roomDescription').textContent=r?descriptions[id]:'Девять пространств для жизни, работы и отдыха.';document.querySelectorAll('#roomNav button').forEach(b=>{b.classList.toggle('active',b.dataset.room===id);b.setAttribute('aria-pressed',b.dataset.room===id?'true':'false');});}
for(const r of ROOMS){const b=document.createElement('button');b.dataset.room=r.id;b.innerHTML=`<small>${r.index}</small><span>${r.shortName||r.name}</span><span class="area-label">${r.area.replace(' м²','')}</span>`;b.addEventListener('click',()=>focusRoom(r.id));$('roomNav').append(b);}
function animateTo(pos,target,duration=850){tween={start:performance.now(),duration,from:camera.position.clone(),to:new THREE.Vector3(...pos),targetFrom:orbit.target.clone(),targetTo:new THREE.Vector3(...target)};}
function home(instant=false){setActive(null);const aspect=viewport.clientWidth/viewport.clientHeight,scale=aspect<.85?Math.min(2.65,1.12/aspect):aspect<1.2?1.17:1;const target=[5.3,0,3.6],p=mode==='top'?[5.3,21*scale,3.61]:[5.3+2.6*scale,15.0*scale,3.6+11.1*scale];if(instant){camera.position.set(...p);orbit.target.set(...target);orbit.update();}else animateTo(p,target);}
function focusRoom(id){const r=roomById(id);if(!r)return;setActive(id);if(mode==='walk')walk.enter(r.walk);else {const [x,z]=r.center,h=viewport.clientWidth<500?10:8;animateTo([x+(mode==='top'?0:1.15),h,z+(mode==='top'?.01:2.15)],[x,0,z]);}if(innerWidth<760){$('mapPanel').hidden=true;$('mapButton').setAttribute('aria-expanded','false');}}
function setMode(next){if(next===mode)return;tween=null;mode=next;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===mode);b.setAttribute('aria-pressed',b.dataset.mode===mode?'true':'false');});document.body.classList.toggle('walk-mode',mode==='walk');$('walkPrompt').hidden=mode!=='walk';$('touchControls').hidden=mode!=='walk';apartment.setCutaway(mode!=='walk');if(mode==='walk'){orbit.enabled=false;camera.fov=64;camera.updateProjectionMatrix();walk.enable();walk.enter(roomById(activeRoom||'living').walk);}else{walk.disable();orbit.enabled=true;orbit.enableRotate=mode!=='top';camera.fov=38;camera.updateProjectionMatrix();home();}renderer.shadowMap.needsUpdate=true;}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
document.querySelectorAll('[data-palette]').forEach(b=>b.addEventListener('click',()=>{palette=b.dataset.palette;apartment.setPalette(palette);document.querySelectorAll('[data-palette]').forEach(n=>{n.classList.toggle('selected',n===b);n.setAttribute('aria-pressed',n===b?'true':'false');});$('paletteText').innerHTML=palette==='warm'?'Светлый дуб, тёплый камень,<br>navy и мягкая охра.':'Дуб, серый камень,<br>глубокий navy и терракота.';}));
$('lightButton').addEventListener('click',()=>{evening=!evening;apartment.setEvening(evening);$('lightButton').textContent=evening?'Вечерний свет':'Дневной свет';$('lightButton').setAttribute('aria-pressed',String(evening));renderer.toneMappingExposure=evening?1.12:1.0;});
for(const name of ['map','help']){$(name+'Button').addEventListener('click',()=>{const panel=$(name+'Panel');panel.hidden=!panel.hidden;$(name+'Button').setAttribute('aria-expanded',String(!panel.hidden));});$('close'+name[0].toUpperCase()+name.slice(1)).addEventListener('click',()=>{$(name+'Panel').hidden=true;$(name+'Button').setAttribute('aria-expanded','false');});}
$('resetButton').addEventListener('click',()=>{if(mode==='walk')setMode('plan');else home();});$('homeLink').addEventListener('click',e=>{e.preventDefault();if(mode==='walk')setMode('plan');else home();});
$('kitchenView').addEventListener('click',()=>{setMode('walk');walk.enter({x:8.05,z:4.76,yaw:Math.PI,pitch:-.13});setActive('living');});
$('captureButton').addEventListener('click',()=>{composer.render();const a=document.createElement('a');a.download=`Oksky-104-${activeRoom||'apartment'}-${palette}.png`;a.href=canvas.toDataURL('image/png');a.click();});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);walk.setKey(b.dataset.key,true);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>walk.setKey(b.dataset.key,false));});
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();pixelRatio=Math.min(devicePixelRatio||1,w<700?1:1.35);renderer.setPixelRatio(pixelRatio);renderer.setSize(w,h,false);composer.setPixelRatio(pixelRatio);composer.setSize(w,h);if(mode!=='walk'&&!activeRoom)home(true);}
new ResizeObserver(resize).observe(viewport);resize();home(true);
THREE.DefaultLoadingManager.onLoad=()=>{$('loading').classList.add('ready');renderer.shadowMap.needsUpdate=true;};
THREE.DefaultLoadingManager.onError=url=>{$('loading').querySelector('p').textContent='Не удалось загрузить материал: '+url;};
const validation=validatePlan();$('routeStatus').textContent=validation.ok?'Все 9 помещений доступны для прогулки':'Проверьте проходимость плана';
const clock=new THREE.Clock();function frame(now){requestAnimationFrame(frame);if(document.hidden||now-frameTime<1000/60-1)return;frameTime=now;const delta=Math.min(.05,clock.getDelta());if(tween&&mode!=='walk'){const v=Math.min(1,(now-tween.start)/tween.duration),t=v*v*(3-2*v);camera.position.lerpVectors(tween.from,tween.to,t);orbit.target.lerpVectors(tween.targetFrom,tween.targetTo,t);if(v===1)tween=null;}if(mode==='walk')walk.update(delta);else orbit.update();composer.render();frameCount++;if(now-sampleTime>1000){fps=Math.round(frameCount*1000/(now-sampleTime));frameCount=0;sampleTime=now;const stat=`${fps} кадр/с · экономный лимит 60`; $('diagnostics').textContent=stat;canvas.dataset.fps=String(fps);canvas.dataset.mode=mode;canvas.dataset.position=`${camera.position.x.toFixed(3)},${camera.position.z.toFixed(3)}`;canvas.dataset.fov=String(camera.fov);}}
requestAnimationFrame(frame);window.addEventListener('blur',()=>walk.keys.clear());document.addEventListener('visibilitychange',()=>{walk.keys.clear();clock.getDelta();});
window.__loftV5={validate:()=>validation,state:()=>({mode,activeRoom,palette,evening,fps,position:camera.position.toArray(),fov:camera.fov})};
